;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	eval-buffer
	meow-append
	meow-back-word
	meow-block
	meow-change
	meow-expand-2
	meow-insert-exit
	meow-left
	meow-next
	meow-next-word
	meow-prev
	meow-right
	meow-undo
	org-ctrl-c-ctrl-c
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	corfu-quit
	markdown-outdent-or-delete
	meow-insert
	term-send-backspace
	term-send-raw
	))
