;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("Stuff I use, 2024 edition"
  (position . 16932)
  (location . "gopher://gopher.beastieboy.net/0/stuffiuse2024.txt")
  (handler . elpher-bookmark-jump))
("Search engine"
 (position . 1)
 (location . "gemini://kennedy.gemi.dev/")
 (handler . elpher-bookmark-jump))
("gemini://geminiprotocol.net/"
 (position . 498)
 (location . "gemini://geminiprotocol.net/")
 (handler . elpher-bookmark-jump))
("gemini://gemini.rahuljuliato.com/"
 (position . 298)
 (location . "gemini://gemini.rahuljuliato.com/")
 (handler . elpher-bookmark-jump))
)
