;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("writing lisp for emacs"
  (front-context-string . "\n1.2 Run a Progr")
  (rear-context-string . "List Processing\n")
  (position . 40645)
  (last-modified 27324 54327 654830 62000)
  (filename . "/usr/share/info/eintr")
  (info-node . "Run a Program")
  (handler . Info-bookmark-jump))
("invadersMain"
 (filename . "~/cpp_projects/Invaders/src/main.cpp")
 (front-context-string . "Player onePlayer")
 (rear-context-string . "include <list>\n\n")
 (position . 251)
 (last-modified 27322 14488 130718 335000))
("Stuff I use, 2024 edition"
 (position . 16932)
 (location . "gopher://gopher.beastieboy.net/0/stuffiuse2024.txt")
 (handler . elpher-bookmark-jump))
("Search engine"
 (position . 1)
 (location . "gemini://kennedy.gemi.dev/")
 (handler . elpher-bookmark-jump))
("gemini://geminiprotocol.net/"
 (position . 498)
 (location . "gemini://geminiprotocol.net/")
 (handler . elpher-bookmark-jump))
("gemini://gemini.rahuljuliato.com/"
 (position . 298)
 (location . "gemini://gemini.rahuljuliato.com/")
 (handler . elpher-bookmark-jump))
)
